### ISSUE TITLE
TypeError: expected dtype object, got 'numpy.dtype[float64]' in eval.py

### ISSUE THREAD

**Issue by zccz6** [chenyilun95/DSGN#23]
When I was testing the model, Typerror appeared.
DSGN/dsgn/eval/kitti-object-eval-python# bash eval.sh /root/autodl-tmp/DSGN/tools/.././outputs/MODEL_DSGN_12g/kitti_output
/root/autodl-tmp/DSGN/tools/.././outputs/MODEL_DSGN_12g/kitti_output
0
Eval 3769 images
Traceback (most recent call last):
  File "evaluate.py", line 32, in <module>
    fire.Fire()
  File "/root/.local/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/.local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/root/.local/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "evaluate.py", line 28, in evaluate
    print(get_official_eval_result(gt_annos, dt_annos, current_class))
  File "/root/autodl-tmp/DSGN/dsgn/eval/kitti-object-eval-python/eval.py", line 773, in get_official_eval_result
    z_center=z_center)
  File "/root/autodl-tmp/DSGN/dsgn/eval/kitti-object-eval-python/eval.py", line 677, in do_eval_v3
    z_center=z_center)
  File "/root/autodl-tmp/DSGN/dsgn/eval/kitti-object-eval-python/eval.py", line 517, in eval_class
    z_center=z_center)
  File "/root/autodl-tmp/DSGN/dsgn/eval/kitti-object-eval-python/eval.py", line 395, in calculate_iou_partly
    overlap_part = image_box_overlap(gt_boxes, dt_boxes)
TypeError: expected dtype object, got 'numpy.dtype[float64]'

**Comment by chenyilun95** [comment]
This could be due to numpy version problem. You might search the related problems in stackoverflow.
